font_family      JetBrainsMonoNL Nerd Font
adjust_line_height		1
# font_family				Monocraft
# adjust_line_height		5
bold_font				auto
italic_font				auto
bold_italic_font		auto
font_size				13
window_padding_width	7
background_opacity		0.81

include mosslight/mosslight3.conf

# allow_remote_control yes
# map cmd+shift+enter new_os_window_with_cwd
map cmd+shift+enter launch --type=background --cwd=current kitty


confirm_os_window_close 0

cursor_trail 1
cursor_trail_decay 0.1 0.2


# optimization
scrollback_lines 2000
sync_to_monitor yes
