# Based on https://github.com/morhetz/gruvbox by morhetz <morhetz@gmail.com>
# Adapted to kitty by wdomitrz <witekdomitrz@gmail.com>

cursor                  #928374
cursor_text_color       background

url_color               #83a598

visual_bell_color       #8ec07c
bell_border_color       #8ec07c

active_border_color     #d3869b
inactive_border_color   #665c54

foreground              #ebdbb2
background              #060606
selection_foreground    #928374
selection_background    #ebdbb2

active_tab_foreground   #fbf1c7
active_tab_background   #665c54
inactive_tab_foreground #a89984
inactive_tab_background #3c3836

# black  (bg3/bg4)
color0                  #282826
color8                  #222222
# red
color1                  #685742
color9                  #685742

#: green
color2                  #5f875f
color10                 #5f875f

# yellow
color3                  #b36d43
color11                 #b36d43

# blue
color4                  #78824b
color12                 #78824b

# purple
color5                  #bb7744
color13                 #bb7744

# aqua
color6                  #c9a554
color14                 #c9a554

# white (fg4/fg3)
color7                  #d7c483
color15                 #d7c483
