# preload = ~/custom/wallpapers/gruvbox/forest-mountain.jpg
# preload = ~/custom/wallpapers/gruvbox/fall.jpg
# wallpaper = HDMI-A-1, ~/custom/wallpapers/gruvbox/fall.jpg
# wallpaper = eDP-1, ~/custom/wallpapers/gruvbox/forest-mountain.jpg

wallpaper {
    monitor = eDP-1
    path = ~/custom/wallpapers/gruvbox/forest-mountain.jpg
    # path = ~/Downloads/amrica.jpg
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/custom/wallpapers/gruvbox/fall.jpg
}

splash = false
