# =-- Executables --= #

exec-once = waybar
exec-once = hyprpaper
exec-once = pactl set-default-sink alsa_output.pci-0000_03_00.6.analog-stereo
exec-once = bash ~/.config/hypr/scripts/battery_notify.sh
exec-once = xrdb -merge ~/.Xresources

