
# === Opacity & Blur ========================================

windowrule = match:class kitty,		opacity 1.0
windowrule = match:class ^(rofi)$,	opacity 0.7 0.7
windowrule = match:class zen,		opacity 0.999999
windowrule = match:class zoom		opacity 0.999999	no_blur = true
windowrule = match:class vlc		opacity 1.0 override 1.0 override

# === Windows Sizes & Floating Rules ========================

windowrule {
	name = picture-in-picture
	match:title = Picture-in-Picture
	size = 426 240
	keep_aspect_ratio = true
	opacity = 1.0 override 1.0 override
	float = true
}

windowrule = match:class qalculate-gtk,			float on, size 800 600
windowrule = match:class org.gnome.Nautilus,	float on, size 800 600
windowrule = match:title Add					float on, size 1024 768

# === Others ================================================

# windowrule {
# 	name = xwayland
# 	match:xwayland = true
# 	match:float = true
# 	fullscreen = false
# 	pin = false
# 	no_focus = true
# }
#windowrule = suppressevent maximize, class:.*
#windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
